apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-training
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/trambtn/solar-prediction.git'
    targetRevision: HEAD
    path: model-training    
  destination:
    server: 'https://kubernetes.default.svc'  
    namespace: default                         
  syncPolicy:
      automated:
        prune: true        
        selfHeal: false
      syncOptions:
        - Replace=true
        - Validate=true
        - CreateNamespace=false
        - PrunePropagationPolicy=foreground
        - PruneLast=truecd